# Netlify Configuration for BlockX React SPA

[build]
  # Build command
  command = "npm run build"
  # Output directory
  publish = "dist"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production build
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_NODE_ENV = "production"
  VITE_API_BASE_URL = "https://block-x-two.vercel.app/api"
  VITE_API_URL = "https://block-x-two.vercel.app/api"
  VITE_BACKEND_URL = "https://block-x-two.vercel.app"
  VITE_FRONTEND_URL = "https://blockx.netlify.app"
  VITE_ENABLE_HTTPS = "true"
  VITE_DEBUG = "false"
  VITE_ENABLE_LOGGING = "false"
  VITE_APP_NAME = "BlockX"
  VITE_APP_VERSION = "1.0.0"

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
